In [1]:
import datetime
from datetime import datetime,date,time,timedelta
c=datetime.now()
print(c)

2026-07-06 21:35:19.075719


In [2]:
print(c.year)

2026


In [3]:
print(c.month)

7


In [4]:
print(c.day)

6


In [5]:
date(2024,1,1)

datetime.date(2024, 1, 1)

In [8]:
time(14,20,20)

datetime.time(14, 20, 20)

In [10]:
m=time(14,20,20)
m.hour,m.minute,m.second


(14, 20, 20)

In [11]:
datetime(2024,1,1,14,20,30)

datetime.datetime(2024, 1, 1, 14, 20, 30)

In [12]:
from datetime import timedelta
timedelta(hours=5)

datetime.timedelta(seconds=18000)

In [13]:
c+timedelta(hours=5)

datetime.datetime(2026, 7, 7, 2, 35, 19, 75719)

In [14]:
c

datetime.datetime(2026, 7, 6, 21, 35, 19, 75719)

In [17]:
#q1.
l1=[1,2,2,3,2,3,4,5]
n={}
for i in l1:
    if i in n:
        n[i]+=1
    else:
        n[i]=1
print(n)        

{1: 1, 2: 3, 3: 2, 4: 1, 5: 1}


In [23]:
t=0
for k,v in n.items():
    if v>t:
        t=v
        ans=k
print("highest is ",ans)        
    

highest is  2


In [25]:
#numpy
import numpy as np
d=np.array([1,2,3,4,5,6,7,8,7])
e=np.array([3,4,5])
print(d+e)
print(d)


[4 6 8]
[1 2 3]


In [26]:
print(d[-1])

3


In [31]:
d.shape

(3,)

In [33]:
d.reshape(3,3)

ValueError: cannot reshape array of size 3 into shape (3,3)

In [34]:
import numpy as np

# Redefine d to have exactly 9 elements (3 * 3 = 9)
d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]) 

# Now this will work
reshaped_d = d.reshape(3, 3)
print(reshaped_d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
